### ISSUE TITLE
Add `files` in package.json

### ISSUE THREAD

**Issue by SimonSchick** [lydell/resolve-url#4]
Heyo:

Currently your package is shipping a bunch of redundant files:
```
node_modules/resolve-url
├── LICENSE
├── bower.json
├── changelog.md
├── component.json
├── package.json
├── readme.md
├── resolve-url.js
└── test
    └── resolve-url.js
```

Please consider adding `files` to `package.json`, in this case `files: []` will do as the `main` is always included when bunding.

**Comment by lydell** [comment]
A PR would be welcome!

**Comment by lydell** [comment]
This package is now deprecated.

**Comment by nzmedet** [comment]
why?
